### ISSUE TITLE
Slow / Failed simulation when using directional derivatives

### ISSUE THREAD

**Issue by DeadParrot** [NREL/SOEP-QSS-Test#2]
Directional derivative support is important in the FMUs used for QSS for accurate event indicator trajectories (needed for zero-crossing protocol robustness) and may be used for state variable second derivatives in future QSS versions. There are a few issues with the current OCT directional derivative support:

* PyFMI runs fail (but not QSS) for some models built with directional derivative support:
  * ASHRAE2006
  * Edit: TwoFloor_TwoZone fails with the OCT-r23206_JM-r14295 build if directional derivatives are enabled with "Evaluating the derivatives failed"

* PyFMI and QSS runs progress very slowly for some models built with directional derivative support:
  * Guideline36
    * Edit: With the OCT-r23206_JM-r14295 update this now fails with "Simulation failed:  'The right-hand side function had repeated recoverable errors. At time 39120.000000.'"
  * Guideline36Spring

* ACControl10 has an event indicator of `time - nextSample` that is not getting the time contribution back from the call for the directional derivatives, breaking the QSS simulations, but the TimeTest model with the same event indicator gets the correct directional derivative

**Comment by DeadParrot** [comment]
### Versions

The issue was observed with these component versions (may occur with others):

Component | Version                            | Date
------------- | --------------------------- | ----------
OCT             | OCT-r23206_JM-r14295  | 2021/05
Buildings     | 9c37781                           | 2021/05/04
QSS             | e4a0f62                            | 2021/06/08

### Build

Build the FMU with `bld` from the OCT directory as described in the [Status](https://github.com/NREL/SOEP-QSS-Test/blob/main/Status.md) page.

### Run

Run the models with PyFMI or QSS from a console configured as described in the [Status](https://github.com/NREL/SOEP-QSS-Test/blob/main/Status.md) page.

**PyFMI**: Use `run` under the model `OCT` directories to generate the CVode simulation.

**QSS**: Use `run` under the model `QSS` directory in a method subdirectory such as `QSS2`.

**Comment by DeadParrot** [comment]
The ACControl10 event indicator noted now gets the correct directional derivatives with the OCT-r28312_JM-r14295 update.

**Comment by DeadParrot** [comment]
With the OCT-r28312_JM-r14295 update the CVode run of the ASHRAE2006 model built with directional derivatives terminates with:
```
Warning: Possible chattering detected at t = 1.308000e+04 in state event(s): [57 59 61 63 65]
Simulation failed:  'The right-hand side function had repeated recoverable errors. At time 39240.000000.
```

**Comment by chria** [comment]
Two bullet split into:

https://github.com/NREL/SOEP-QSS-Test/issues/22
https://github.com/NREL/SOEP-QSS-Test/issues/21

rest is fixed.
