### ISSUE TITLE
Compiler option to specify additional output variables

### ISSUE THREAD

**Issue by chria** [NREL/SOEP-QSS-Test#7]
It would help with QSS efficiency to be able to indicate to the FMU build process to treat specified local variables as output variables so that dependencies are present in the modelDescription.xml file (to avoid a very inefficient QSS process for getting local variable outputs)

**Comment by DeadParrot** [comment]
This issue has been made moot by the addition of an OCT FMU build option to add a `<Dependencies>` annotation section that includes local variables and their dependencies.
